#!/usr/bin/env PATH=/bin:/sbin:/usr/bin:/usr/local/bin /Users/imbriaco/.rbenv/shims/ruby

# Make sure we're in the top-level directory for the command
# since so many paths are relative.
Dir.chdir(File.dirname(__FILE__))

# Add the Bundle's lib directory to the Ruby load path
$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), 'lib'))

require 'bundler/setup'
require 'cog'

Cog.bundle('imbriaco')
